# Generated by Django 3.0.2 on 2020-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_delete_shelters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('manager', models.CharField(max_length=100)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cats', models.ManyToManyField(to='animals.Cats')),
                ('dogs', models.ManyToManyField(to='animals.Dogs')),
                ('reptiles', models.ManyToManyField(to='animals.Reptiles')),
            ],
        ),
    ]
