# Generated by Django 3.0.2 on 2020-01-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelters',
        ),
    ]
